<?php

function los_register_posttypes() {
    $labels = [
        "name" => __( "Personen", "los" ),
        "singular_name" => __( "Person", "los" ),
        "menu_name" => __( "Personen", "los" ),
        "all_items" => __( "All Personen", "los" ),
        "add_new" => __( "Add new", "los" ),
        "add_new_item" => __( "Add new Person", "los" ),
        "edit_item" => __( "Edit Person", "los" ),
        "new_item" => __( "New Person", "los" ),
        "view_item" => __( "View Person", "los" ),
        "view_items" => __( "View Personen", "los" ),
        "search_items" => __( "Search Personen", "los" ),
        "not_found" => __( "No Personen found", "los" ),
        "not_found_in_trash" => __( "No Personen found in trash", "los" ),
        "parent" => __( "Parent Person:", "los" ),
        "featured_image" => __( "Featured image for this Person", "los" ),
        "set_featured_image" => __( "Set featured image for this Person", "los" ),
        "remove_featured_image" => __( "Remove featured image for this Person", "los" ),
        "use_featured_image" => __( "Use as featured image for this Person", "los" ),
        "archives" => __( "Person archives", "los" ),
        "insert_into_item" => __( "Insert into Person", "los" ),
        "uploaded_to_this_item" => __( "Upload to this Person", "los" ),
        "filter_items_list" => __( "Filter Personen list", "los" ),
        "items_list_navigation" => __( "Personen list navigation", "los" ),
        "items_list" => __( "Personen list", "los" ),
        "attributes" => __( "Personen attributes", "los" ),
        "name_admin_bar" => __( "Person", "los" ),
        "item_published" => __( "Person published", "los" ),
        "item_published_privately" => __( "Person published privately.", "los" ),
        "item_reverted_to_draft" => __( "Person reverted to draft.", "los" ),
        "item_scheduled" => __( "Person scheduled", "los" ),
        "item_updated" => __( "Person updated.", "los" ),
        "parent_item_colon" => __( "Parent Person:", "los" ),
    ];
    
    $args = [
        "label" => __( "Personen", "los" ),
        "labels" => $labels,
        "description" => "",
        "public" => true,
        "publicly_queryable" => true,
        "show_ui" => true,
        "show_in_rest" => true,
        "rest_base" => "",
        "rest_controller_class" => "WP_REST_Posts_Controller",
        "has_archive" => false,
        "show_in_menu" => true,
        "show_in_nav_menus" => true,
        "delete_with_user" => false,
        "exclude_from_search" => false,
        "capability_type" => "post",
        "map_meta_cap" => true,
        "hierarchical" => false,
        "rewrite" => [ "slug" => "person", "with_front" => true ],
        "query_var" => true,
        "menu_icon" => "dashicons-universal-access",
        "supports" => [ "title" ],
        "show_in_graphql" => false,
    ];
    
    register_post_type( "person", $args );
    
    /**
     * Post Type: Events.
     */
    
    $labels = [
        "name" => __( "Events", "los" ),
        "singular_name" => __( "Event", "los" ),
        "menu_name" => __( "Events", "los" ),
        "all_items" => __( "All Events", "los" ),
        "add_new" => __( "Add new", "los" ),
        "add_new_item" => __( "Add new Event", "los" ),
        "edit_item" => __( "Edit Event", "los" ),
        "new_item" => __( "New Event", "los" ),
        "view_item" => __( "View Event", "los" ),
        "view_items" => __( "View Events", "los" ),
        "search_items" => __( "Search Events", "los" ),
        "not_found" => __( "No Events found", "los" ),
        "not_found_in_trash" => __( "No Events found in trash", "los" ),
        "parent" => __( "Parent Event:", "los" ),
        "featured_image" => __( "Featured image for this Event", "los" ),
        "set_featured_image" => __( "Set featured image for this Event", "los" ),
        "remove_featured_image" => __( "Remove featured image for this Event", "los" ),
        "use_featured_image" => __( "Use as featured image for this Event", "los" ),
        "archives" => __( "Event archives", "los" ),
        "insert_into_item" => __( "Insert into Event", "los" ),
        "uploaded_to_this_item" => __( "Upload to this Event", "los" ),
        "filter_items_list" => __( "Filter Events list", "los" ),
        "items_list_navigation" => __( "Events list navigation", "los" ),
        "items_list" => __( "Events list", "los" ),
        "attributes" => __( "Events attributes", "los" ),
        "name_admin_bar" => __( "Event", "los" ),
        "item_published" => __( "Event published", "los" ),
        "item_published_privately" => __( "Event published privately.", "los" ),
        "item_reverted_to_draft" => __( "Event reverted to draft.", "los" ),
        "item_scheduled" => __( "Event scheduled", "los" ),
        "item_updated" => __( "Event updated.", "los" ),
        "parent_item_colon" => __( "Parent Event:", "los" ),
    ];
    
    $args = [
        "label" => __( "Events", "los" ),
        "labels" => $labels,
        "description" => "",
        "public" => true,
        "publicly_queryable" => true,
        "show_ui" => true,
        "show_in_rest" => true,
        "rest_base" => "",
        "rest_controller_class" => "WP_REST_Posts_Controller",
        "has_archive" => false,
        "show_in_menu" => true,
        "show_in_nav_menus" => true,
        "delete_with_user" => false,
        "exclude_from_search" => false,
        "capability_type" => "post",
        "map_meta_cap" => true,
        "hierarchical" => false,
        "rewrite" => [ "slug" => "event", "with_front" => true ],
        "query_var" => true,
        "menu_icon" => "dashicons-calendar-alt",
        "supports" => [ "title", "thumbnail" ],
        "show_in_graphql" => false,
    ];
    
    register_post_type( "event", $args );
}